sudo: false
language: node_js
node_js:
- 9.3.0
os:
- osx
before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
  sh -e /etc/init.d/xvfb start; sleep 3; fi
install:
- npm install
script:
- npm test
after_success:
- npm run semantic-release
env:
  global:
  - secure: im3vniEtFXLCwRqWRryeLvn0ToOPGu01CtEYLyREFcQ5ZIe6EPAasSwh3byxlW97g33ccu+M07YFCc6Ohup8LkM3SLExn87g/Y4sFOBBLU1WNeFHnslol4jc9WI5ClvP9EICVzZL5NlZA5hyfp6T5CH4nSzNfoQTeskTaayzA45TJGSQSj6qRdBuPMXKPQQtT3HZtu/Afv82n2S5UUQIXGd9dQpqz3e4/PKEnlH9k4xkj3FkXXAMHAVrnZRErmLOhdfCyMki1XAIgbKV46tecrDMFSs6RN2FtSkWagPjkkOEN1pVxQEHmMUoq893XLDRATd054wjmXOFGnv2HUH18CUUdHVGhLPaleBIBeQkIjuLkExv9wz9INTraK7hIKFabSxRRraH2mV3fBhyhMER4GnGxEnc1U3XuG68Jio0sPmrFaeI3PSH20R0fKgBDIlFC5Bvw4e8VSjglPfTMyAGzkgfdlCzHodfQ19mqJpR2CofK1HtS8hUD8K7Uv5fSCaXWZXAwqE52J2ic9en7Dhe8qUSzT8FlVedk9vuAkI0gVqLIK7Mn2U1nx8yQNpUPkqlTgBPCr9v9Eq5RS5pn6LmkyDcXhNJkZDTTxtLh5weoVcONdM6boYHfTIE525mqDO1xJYpmW08LFW2SHbnjohV+ipSg0vqlUeQnebBRV9DoP8=
  - secure: VctDv3nzObivx+T1T7lY0dXxzMinBB+kd5ACoslPOw7ziQJS0uTL3SZxZcGeEQKjkraq9zSVL6gMgrUp+M5tVd+iWJHTqO06D8IxM9pbutCpd2lCQ1yAqGZSx7gT0MCWjWGDYsWCPLGOQHLf51Qol4pruKEJJ7xhFtBFHsginTMh+9HJYONd/cTcKaer52AuFfuEOCI7C48ZBcwQWPZMitE9ONeipiRO1uQuhq9VMqs7+mF8ArmrUls8KKjaoGxcmazOGO/9tggqGJdGakPnZy0qGVkKZhNyvD9wKY112j6JHXzAygGgsSxtLAqECjuS3fvqN45w/kLA8yLuhbotlMwCMwnjORB5o5EjegG7T+RIsXHMS+QiZG4QEfmWOWlW96UWbVCZpEnoay/K/9LuhGuKD+8AZrnqFYmgxTkoLbchMuPHTgwlSbcMCng3okxW84aZjQOLOn862AWZW06UT4mRMxQa5slOrHW7Ca81WjPBQBWwHH9gw/Sr7gXGc9LECLBkL5zsA4tyOBVXU4IpitXnBy/7qiV0eAce94XMZw6HknjZOHrl4grWJBuqcN6fNca19wvsadIZGVMiL3w0m+As7YeR+TZnxsIvYTy3e5vEaCQ2iN6YfH2eVebeeAD2+pCuvOJK5i6P2LAI7Vg05UjM8ZEZGzL8H6hNqn3BDWs=
