sudo: false
language: node_js
node_js:
- 9.3.0
os:
- osx
before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
  sh -e /etc/init.d/xvfb start; sleep 3; fi
install:
- npm install
script:
- npm test
after_success:
- npm run semantic-release
env:
  global:
  - secure: im3vniEtFXLCwRqWRryeLvn0ToOPGu01CtEYLyREFcQ5ZIe6EPAasSwh3byxlW97g33ccu+M07YFCc6Ohup8LkM3SLExn87g/Y4sFOBBLU1WNeFHnslol4jc9WI5ClvP9EICVzZL5NlZA5hyfp6T5CH4nSzNfoQTeskTaayzA45TJGSQSj6qRdBuPMXKPQQtT3HZtu/Afv82n2S5UUQIXGd9dQpqz3e4/PKEnlH9k4xkj3FkXXAMHAVrnZRErmLOhdfCyMki1XAIgbKV46tecrDMFSs6RN2FtSkWagPjkkOEN1pVxQEHmMUoq893XLDRATd054wjmXOFGnv2HUH18CUUdHVGhLPaleBIBeQkIjuLkExv9wz9INTraK7hIKFabSxRRraH2mV3fBhyhMER4GnGxEnc1U3XuG68Jio0sPmrFaeI3PSH20R0fKgBDIlFC5Bvw4e8VSjglPfTMyAGzkgfdlCzHodfQ19mqJpR2CofK1HtS8hUD8K7Uv5fSCaXWZXAwqE52J2ic9en7Dhe8qUSzT8FlVedk9vuAkI0gVqLIK7Mn2U1nx8yQNpUPkqlTgBPCr9v9Eq5RS5pn6LmkyDcXhNJkZDTTxtLh5weoVcONdM6boYHfTIE525mqDO1xJYpmW08LFW2SHbnjohV+ipSg0vqlUeQnebBRV9DoP8=
  - secure: H1aUDcV96huqAFfaPQ1SipYrFPOxwR8Dp7yPSjMtWI0V3CspCxdeJC0SAECLqcnOvIU2nGYB1ppd2dUw5JEZwp8YVzteWMmfSmkR3WxqP+Zng9GlCNo41RqNyZjsnvcvUvGOLYmZmB0q3xh6v1ROT6qEVDjKyzYwPNt6hYEuWb1nW5T+sq2wgCeYoZepv9Q9+PHWXyMoRwB/D37xseksdZZlaal4695SYZNIMP6kTRTrkSBCT4L0af+HOYR3XDmZjESI6SJyy4bqgkXPeM9OBbh+czKacRgG+adSrgksbc1jNrbV/j8anQYSdjgyzPpT9fqVHEn+nY/2o9nseoqQFe0xjN/btvVbnxa80TN+Q1o6ilknipPDPn3K/USm3eIg5UmLQVxaJ9cpsFCDBc+PcGGswbnmsVPMZjhTnrZfGvs96f7pj0APQVHCj3PAKm6p8MWDnMLQ4gW5j3ExAxACsHLfkuM2PKpRG+VnrF2/WzvBQmcUz96DX0Uc5zhBrO50X9bJst2f5Kt1Li2Qocfn70EAhk9C7KnnD4ssT4+3QntYZVIiTJvgAoclefO/OoqCpT3H9+gswF6JZ6JJuNcROEPnisuAbOTFwvfU12BfLa2imcmnTvxEMAj6epqmH0dz8/sYeHIb9s63oLNHGRDIf4Ir3wdB2VRppKT7RAsQpxs=
