sudo: false
language: node_js
node_js:
  - 9.3.0
os:
  - osx
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start; sleep 3; fi
install:
  - npm install
script:
  - npm test
after_success:
  - npm run semantic-release
env:
  global:
    - secure: im3vniEtFXLCwRqWRryeLvn0ToOPGu01CtEYLyREFcQ5ZIe6EPAasSwh3byxlW97g33ccu+M07YFCc6Ohup8LkM3SLExn87g/Y4sFOBBLU1WNeFHnslol4jc9WI5ClvP9EICVzZL5NlZA5hyfp6T5CH4nSzNfoQTeskTaayzA45TJGSQSj6qRdBuPMXKPQQtT3HZtu/Afv82n2S5UUQIXGd9dQpqz3e4/PKEnlH9k4xkj3FkXXAMHAVrnZRErmLOhdfCyMki1XAIgbKV46tecrDMFSs6RN2FtSkWagPjkkOEN1pVxQEHmMUoq893XLDRATd054wjmXOFGnv2HUH18CUUdHVGhLPaleBIBeQkIjuLkExv9wz9INTraK7hIKFabSxRRraH2mV3fBhyhMER4GnGxEnc1U3XuG68Jio0sPmrFaeI3PSH20R0fKgBDIlFC5Bvw4e8VSjglPfTMyAGzkgfdlCzHodfQ19mqJpR2CofK1HtS8hUD8K7Uv5fSCaXWZXAwqE52J2ic9en7Dhe8qUSzT8FlVedk9vuAkI0gVqLIK7Mn2U1nx8yQNpUPkqlTgBPCr9v9Eq5RS5pn6LmkyDcXhNJkZDTTxtLh5weoVcONdM6boYHfTIE525mqDO1xJYpmW08LFW2SHbnjohV+ipSg0vqlUeQnebBRV9DoP8=
    - secure: dgX/ehjuKZzroyJgaxOJUcm2nypK4tGzLPtVCGk8WAFYg/iFZ+sb+H0oA407x1SZdjE54g5DA1xiBFZs7wxql1rg07OCW9yufBt/b8FJYdt8s+Po62RmxEGjR+eK35QQhDUd0n1GEcHKkzh0Y/BaJEImXhuxkuVVg/Te+u3e26l5ND/gAOeiFDfT37YWoHQkcx4jEdSLvVwhDqG6PlvNFBIPkFi5sSpbEFZyS/AmPmr0iJbUpV27MrgoFsiHjayIjFZw676BLl4TES4daYf1VmjdR3utfRE7pHa8LDp70IA5YWvgFTyOhdF1i7QCVqWnNdj7FHXLSBT3lbNIxan5txILpLXAkZ5uUrwyKDEPlrhjxRltMIzyISNolUxYgREihFxUHSNxXeuUFRsMcjcHWJvrp7VbSSkmDuFgdX+GfCU0DK5zopZlUYHLbizQzDdoHrCAPwSxIz74avDpx4dWxG2tTVNJ1v9JE/9dG70yCoghp1rFd4nYAgC933q9XMU10pGFATMGR6XBZtyaZiJfz4Rr6TVRtH5viFKKIyOxHVsr5PO+MBVF2F/BqdOMfOy7VEQMchsChy5lePae5/XVEzlUfVEfujQgW0FGB0sv8qlh3rDcK3aI7CGbcyn+K1cE0tVmqAQMq6nhZwOwECGr84xKzRFa3EeQvGdJvM2Bcfg=
