sudo: false
language: node_js
node_js:
  - 9.3.0
os:
  - osx
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start; sleep 3; fi
install:
  - npm install
script:
  - npm test
after_success:
  - npm run semantic-release
env:
  global:
    - secure: im3vniEtFXLCwRqWRryeLvn0ToOPGu01CtEYLyREFcQ5ZIe6EPAasSwh3byxlW97g33ccu+M07YFCc6Ohup8LkM3SLExn87g/Y4sFOBBLU1WNeFHnslol4jc9WI5ClvP9EICVzZL5NlZA5hyfp6T5CH4nSzNfoQTeskTaayzA45TJGSQSj6qRdBuPMXKPQQtT3HZtu/Afv82n2S5UUQIXGd9dQpqz3e4/PKEnlH9k4xkj3FkXXAMHAVrnZRErmLOhdfCyMki1XAIgbKV46tecrDMFSs6RN2FtSkWagPjkkOEN1pVxQEHmMUoq893XLDRATd054wjmXOFGnv2HUH18CUUdHVGhLPaleBIBeQkIjuLkExv9wz9INTraK7hIKFabSxRRraH2mV3fBhyhMER4GnGxEnc1U3XuG68Jio0sPmrFaeI3PSH20R0fKgBDIlFC5Bvw4e8VSjglPfTMyAGzkgfdlCzHodfQ19mqJpR2CofK1HtS8hUD8K7Uv5fSCaXWZXAwqE52J2ic9en7Dhe8qUSzT8FlVedk9vuAkI0gVqLIK7Mn2U1nx8yQNpUPkqlTgBPCr9v9Eq5RS5pn6LmkyDcXhNJkZDTTxtLh5weoVcONdM6boYHfTIE525mqDO1xJYpmW08LFW2SHbnjohV+ipSg0vqlUeQnebBRV9DoP8=
    - secure: MAeaad9l9FIk08fCyyC/bnCZmsWZw7xcjJnjQFDTYDDp9A1qd6joXBn5lyjYhQWe4EJ6qY7RaRpUCMidF5pchj2hgIe71AIQRzhVy0zBjwFkYwsI3zI2RKKLPmpJCvMRg4phKKPFghkDoX6WuQijZnjtiVm7v/8P4iizkxAxmLRedTWk7g+p+2ukqIV/aurc1yHc6v4fmfsrdRxj8L9xeV60kiKIPVd/0CX9z3GKCgx95aw4rFi7zBGBqH3YZBqnegg6pSmNEYYlKPb5D6ALlc43C/sSLKFer9r2q/gE+TQkGvxmDNNv3SCYRdn9/m2PnJFKOmkuTrhXZAjfTyERlwOQO3nuqBJffG6O5CkL4yXF7wjn28belUhtH9jF31LwiEf6xN5yBG6JMHPGX8d+g+BU8Yco9+GsfTOvG3jdSJCuxE/2nCCI8Rk8f9PmZjqi0cMhZfvbrS0OfD0pX7n1iYRUX0cWOA63+ue5N0y2ozbFq5efkKps2xmjUbJmm7WPLqgws0mCeYVydve9+HXINR3ZMiCH2u/jBpD37D5zfTFC9IorssyGmH9KaByRQopJMPZNvIp0NEgW0iZkHSzC8epTzSUXddj449mXydpC2dNTXk07Pai1+ZGfuUckJfpfFsDpXFOnCWK+RdXXYjxy2CM629iMxQGPGFLxdfsY9xU=
    - secure: sPbPUJcMeZTRRttnZw4VxraN2Zd1jmiq3QWPDvlhXs9OxGRZlZZC1sJRQvvneqTrUwx/JttsB/6rd8Sr2LSdcHalIzKDVFA7ntnKNXm5+eQu1kk1G4s6I/pD+NUN819hZPDLDKxttj9nuqC8go/9Leu3SgWBCR6GWHp00trYTdL6vDywJk2IGbhvDH+rahp9NouXowiL2tZdxj3KI7gv4ZrV9LpgsWx+fTbFMoOWievGfdMLvPsbX5yxBov/FvQreFhiKUFZHMBIwR54mIXIc+157NXBXiJ02K6d65nJd6MVXCKuotVF00Y+a7cvOI/MjPpTeldwQTn/8WldFievRgJX8/q6j8V/o9GL1MiwI7IyhOyBS54kT24MUHjH4EsvmXMzCZAWN+CQnM0MeHpacIm5qY74QAMVJlptav1UWzXiDu13Ckk7C0kHAyucvQnFLz0m8pLqG86edmeRJjaLgSEyXDU+IeCYsb7DSG1wL6hShG26Ryp4DEX99WvEy2ae59mabJQbD+2x7FJdOHswvJ8QkWtdNZLd3TpsUz5IsZkB8Kvbk6T6V48D57ZhRcIfscL6590cc0f1POfM0ns7UR7bpX42QQJ1TDCQQC/KFaJGCKAjyNSOXa7k3egPFg4KuSYlKBGDM5DVZAutoJYShULaVnAU9exv2e9Uztbatgg=
