sudo: false
language: node_js
node_js:
- 9.3.0
os:
- osx
before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
  sh -e /etc/init.d/xvfb start; sleep 3; fi
install:
- npm install
script:
- npm test
after_success:
- npm run semantic-release
env:
  global:
  - secure: im3vniEtFXLCwRqWRryeLvn0ToOPGu01CtEYLyREFcQ5ZIe6EPAasSwh3byxlW97g33ccu+M07YFCc6Ohup8LkM3SLExn87g/Y4sFOBBLU1WNeFHnslol4jc9WI5ClvP9EICVzZL5NlZA5hyfp6T5CH4nSzNfoQTeskTaayzA45TJGSQSj6qRdBuPMXKPQQtT3HZtu/Afv82n2S5UUQIXGd9dQpqz3e4/PKEnlH9k4xkj3FkXXAMHAVrnZRErmLOhdfCyMki1XAIgbKV46tecrDMFSs6RN2FtSkWagPjkkOEN1pVxQEHmMUoq893XLDRATd054wjmXOFGnv2HUH18CUUdHVGhLPaleBIBeQkIjuLkExv9wz9INTraK7hIKFabSxRRraH2mV3fBhyhMER4GnGxEnc1U3XuG68Jio0sPmrFaeI3PSH20R0fKgBDIlFC5Bvw4e8VSjglPfTMyAGzkgfdlCzHodfQ19mqJpR2CofK1HtS8hUD8K7Uv5fSCaXWZXAwqE52J2ic9en7Dhe8qUSzT8FlVedk9vuAkI0gVqLIK7Mn2U1nx8yQNpUPkqlTgBPCr9v9Eq5RS5pn6LmkyDcXhNJkZDTTxtLh5weoVcONdM6boYHfTIE525mqDO1xJYpmW08LFW2SHbnjohV+ipSg0vqlUeQnebBRV9DoP8=
  - secure: btcadT1N1H2GrJFifUGr8F2Vtq9PgB2yjOh2TLLeOgYdwRXzv2vKQG7gN0TXL753rkBt4MRAMhR/5bLfwqtqBymsw6Gnyze1E243cfLEP8OGLN9Lp0jyNU51RrHZH3DEE9AWnAaOIml0tyDCK86YW1hnYugKbz75m98rVsCn35+K7N35uleNIk99jQEkT1tcyMVwLwEjES06RRQa0f9oQ9ZPzQTHEVDzXIRHAN5rRXtBrSLHt2AHndOkMjMtQFbacPbO6MEgamXT7modzTeNF/gNMEJuogAvxsPaf/bOIW0PK6NK7bsWKzy5U8Kajiv78Ml83UO5bxbHmAKo81j62KGIPELNzppn2iUG4Hg4YURIVj35q0G51ErWKfgjHxRT9sts/lxg2vEgM4/mr3abjtv6mOXGpJWfXmQZXvNkOKwTY0BSGIGhUZa8hRQh5X3NX1mOtdcKXOo2gdxUJUULn49i0hekiQjcfJFYCJAI0zeUwuYRGjcnMuj1xkRGP/i84yVt8ZlN/bM9oorMi2Nx6dBGfbGWZyAukb7LSlW3LvLbYgL9g9AnY7LLxifGUN/hmr6J//iELQpZ0X+HsB/VVUgsYtuDX1nfOWaaP41j2YgK1Eu+ftBw9pm68xgXpYX55InJFo/OOYt4HYMMCH5kfBmlL5lISArBzoDRcqmzJjg=
